### ISSUE TITLE
Printing continuously "File association not found for extension .py" during downloading

### ISSUE THREAD

**Issue by mvanlierBCG** [DmitryRyumin/OIDv6#1] opened 2020-07-13 09:45 UTC
Printing continuously "File association not found for extension .py" during downloading.

OS: Windows 10 Pro 2004
Python: Anaconda 3.7

**Comment by DmitryRyumin** [comment] 2020-07-13 14:20
> Printing continuously "File association not found for extension .py" during downloading.
> 
> OS: Windows 10 Pro 2004
> Python: Anaconda 3.7

How do you run the download? I checked in the anaconda and everything works

![Example](https://raw.githubusercontent.com/DmitryRyumin/OIDv6/master/Iss/1.png)

**Comment by alhabshi3k** [comment] 2020-09-28 15:10
I have the same problem, Although I am not using anaconda but WinPython 3.8.5.
The origin of the problem is from awscli, refer to issue [#3518](https://github.com/aws/aws-cli/issues/3518). 

A quick solution is to include the following code into Anaconda environment settings

```cmd
assoc .py=pyautofile
ftype pyautofile="C:\Anaconda3\python.exe" "%1" %*
```

References:
- https://github.com/aws/aws-cli/issues/3518
- https://stackoverflow.com/questions/47459536/file-association-not-found-for-extension-py

**Closed as completed** 2023-09-25 21:00 UTC
